modules:
  github-pull-request-initial-comment:
    enabled: true
    capabilities:
      create-pull-request-comment:
        body: "Thanks for opening this pull request. We'll take a look shortly."

  github-issue-initial-comment:
    enabled: true
    capabilities:
      create-issue-comment:
        body: "Thanks for opening this issue. We'll take a look shortly."
